### ISSUE TITLE
OutputDistributionCallback

### ISSUE THREAD

**Issue by I8dNLo** [BloodAxe/Catalyst-Inria-Segmentation-Example#1]
Hi. 
Trying to reconstruct your solution. Looks like a wrong version of toolbelt in requirements.
I'm trying to run fit_predict.py and getting import error at this line:

> from pytorch_toolbelt.utils.catalyst.metrics import OutputDistributionCallback

can you give advice about the correct setup?
`ImportError: cannot import name 'OutputDistributionCallback' from 'pytorch_toolbelt.utils.catalyst.metrics' `

**Comment by BloodAxe** [comment]
Greetings! 

Thanks for your issue report. It seems, a draft code from feature branch had squeezed into main branch. I removed that import, it should run.
Have you encounter any new issues, try installing pytorch-toolbelt from the feature/hourglass branch: https://github.com/BloodAxe/pytorch-toolbelt/tree/feature/hourglass
