### ISSUE TITLE
StackedHGEncoder import error

### ISSUE THREAD

**Issue by I8dNLo** [BloodAxe/Catalyst-Inria-Segmentation-Example#2]
Hi
Looks like there no StackedHGEncoder in pytorch_toolbelt.modules.encoders. 
I tried to find it in a previous version of the toolbelt but not succeed. 

inria/models/hg.py
`from pytorch_toolbelt.modules.encoders import EncoderModule, StackedHGEncoder`

> ImportError: cannot import name 'StackedHGEncoder'

**Comment by BloodAxe** [comment]
This should be fixed since https://github.com/BloodAxe/Catalyst-Inria-Segmentation-Example/commit/6e1d47ad2d7699587de9432a56a12d4f9b327702
StackedHGEncoder has been added in pytorch-toolbelt==0.3.2 (Requirements file is also updated).
