### ISSUE TITLE
tiles training mode

### ISSUE THREAD

**Issue by I8dNLo** [BloodAxe/Catalyst-Inria-Segmentation-Example#3]
In inria/dataset at "tiles" training mode the last usage of the returned sampler is 
`train_sampler = None` 
but 
> torch/utils/data/sampler

expects it to be a positive integer.
> ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by BloodAxe** [comment]
This should be fixed since https://github.com/BloodAxe/Catalyst-Inria-Segmentation-Example/commit/6e1d47ad2d7699587de9432a56a12d4f9b327702
