### ISSUE TITLE
Data path and structure

### ISSUE THREAD

**Issue by Servando1990** [BloodAxe/Catalyst-Inria-Segmentation-Example#4]
Hi!

Could you specify where does the path to INRIA dataset is supposed to be?

Thanks

**Comment by BloodAxe** [comment]
Anywhere on the file system where it is convenient to you. You should unzip all archives to get folder with "train" and "test" directories. This folder is your root data directory, which may be passed via "`-dd /path/to/data`" or by setting environment variable `INRIA_DATA_DIR`.

**Comment by Servando1990** [comment]
thanks!
