### ISSUE TITLE
Dataloader in PyTorch

### ISSUE THREAD

**Issue by xdtl** [BloodAxe/Catalyst-Inria-Segmentation-Example#9]
This may affect data augmentation: https://tanelp.github.io/posts/a-bug-that-plagues-thousands-of-open-source-ml-projects/

**Comment by BloodAxe** [comment]
This repo is not affected by a well-known behavior of np.random under multiprocessing in python.

**Comment by xdtl** [comment]
It's good to know that. Thanks!
